/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class grgr_f2f2019_n_NativeBridge */

#ifndef _Included_grgr_f2f2019_n_NativeBridge
#define _Included_grgr_f2f2019_n_NativeBridge
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     grgr_f2f2019_n_NativeBridge
 * Method:    helloNative
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_grgr_f2f2019_n_NativeBridge_helloNative
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
