/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class grgr_f2f2019_n_NativeBridge */

#ifndef _Included_grgr_f2f2019_n_NativeBridge
#define _Included_grgr_f2f2019_n_NativeBridge
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     grgr_f2f2019_n_NativeBridge
 * Method:    helloNative
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_grgr_f2f2019_n_NativeBridge_helloNative
  (JNIEnv *, jobject, jstring);

/*
 * Class:     grgr_f2f2019_n_NativeBridge
 * Method:    helloNativeWithCallback
 * Signature: (Ljava/lang/String;Ljava/lang/ClassLoader;)V
 */
JNIEXPORT void JNICALL Java_grgr_f2f2019_n_NativeBridge_helloNativeWithCallback
  (JNIEnv *, jobject, jstring, jobject);

/*
 * Class:     grgr_f2f2019_n_NativeBridge
 * Method:    processInformation
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_grgr_f2f2019_n_NativeBridge_processInformation
  (JNIEnv *, jobject);

/*
 * Class:     grgr_f2f2019_n_NativeBridge
 * Method:    pthreads
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_grgr_f2f2019_n_NativeBridge_pthreads
  (JNIEnv *, jobject);

/*
 * Class:     grgr_f2f2019_n_NativeBridge
 * Method:    pthreadsAttached
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_grgr_f2f2019_n_NativeBridge_pthreadsAttached
  (JNIEnv *, jobject);

/*
 * Class:     grgr_f2f2019_n_NativeBridge
 * Method:    pthreadsAll
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_grgr_f2f2019_n_NativeBridge_pthreadsAll
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
